### ISSUE TITLE
Pretrained VGG model link

### ISSUE THREAD

**Issue by richardminh** [beeps82/SVHN_CNN#2]
Hello, Beeps82. How are you?
I  have a great interesting about your project. 
Your project is amazing for digit detect & recognition. But i can't running your application coz of there are no required/VGGPreTrained.classifier.hdf5 file. 
Can you provide me it's link or file?
Hope hearing good news from you soon.
Thanks.

**Comment by beeps82** [comment]
Uploaded https://my.pcloud.com/publink/show?code=kZsPnA7ZuMoiRGBAw0X4k7lGrU2CyFH2liey
